2025-04-25 22:52:07.196 [info] Started local extension host with pid 4984.
2025-04-25 22:52:07.525 [error] Extension 'ms-python.debugpy CANNOT USE these API proposals 'portsAttributes, debugVisualization, contribViewsWelcome'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
2025-04-25 22:52:07.525 [error] Extension 'ms-python.python CANNOT USE these API proposals 'contribEditorContentMenu, quickPickSortByLabel, testObserver, quickPickItemTooltip, terminalDataWriteEvent, terminalExecuteCommandEvent, codeActionAI, notebookReplDocument, notebookVariableProvider'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
2025-04-25 22:52:07.552 [error] [ms-python.python]: editor/content is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["contribEditorContentMenu"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-python.python
2025-04-25 22:52:09.121 [error] An unknown error occurred. Please consult the log for more details.
2025-04-25 22:52:09.876 [info] [perf] Render performance baseline is 18ms
2025-04-25 23:24:27.614 [error] ValueError: `column` parameter (31) is not in a valid range (0-17) for line 90 ('    def iterador(\n').: Error: ValueError: `column` parameter (31) is not in a valid range (0-17) for line 90 ('    def iterador(\n').
	at ae (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
	at oe (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
	at Immediate.<anonymous> (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
	at process.processImmediate (node:internal/timers:483:21)
2025-04-25 23:24:38.732 [error] ValueError: `column` parameter (31) is not in a valid range (0-17) for line 90 ('    def iterador(\n').: Error: ValueError: `column` parameter (31) is not in a valid range (0-17) for line 90 ('    def iterador(\n').
	at ae (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
	at oe (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
	at Immediate.<anonymous> (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
	at process.processImmediate (node:internal/timers:483:21)
2025-04-25 23:24:40.340 [error] ValueError: `column` parameter (31) is not in a valid range (0-17) for line 90 ('    def iterador(\n').: Error: ValueError: `column` parameter (31) is not in a valid range (0-17) for line 90 ('    def iterador(\n').
	at ae (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
	at oe (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
	at Immediate.<anonymous> (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
	at process.processImmediate (node:internal/timers:483:21)
2025-04-25 23:25:02.833 [error] ValueError: `column` parameter (31) is not in a valid range (0-17) for line 90 ('    def iterador(\n').: Error: ValueError: `column` parameter (31) is not in a valid range (0-17) for line 90 ('    def iterador(\n').
	at ae (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
	at oe (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
	at Immediate.<anonymous> (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
	at process.processImmediate (node:internal/timers:483:21)
2025-04-25 23:25:04.423 [error] ValueError: `column` parameter (31) is not in a valid range (0-17) for line 90 ('    def iterador(\n').: Error: ValueError: `column` parameter (31) is not in a valid range (0-17) for line 90 ('    def iterador(\n').
	at ae (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
	at oe (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
	at Immediate.<anonymous> (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
	at process.processImmediate (node:internal/timers:483:21)
2025-04-25 23:52:15.712 [error] AttributeError: 'Newline' object has no attribute 'children': Error: AttributeError: 'Newline' object has no attribute 'children'
	at ae (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
	at oe (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
	at Immediate.<anonymous> (/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
	at process.processImmediate (node:internal/timers:483:21)
