2025-04-25 00:34:13.354 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "724"

2025-04-25 00:34:20.072 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "744"

2025-04-25 00:34:34.569 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "780"

2025-04-25 00:34:52.956 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "819"

2025-04-25 00:35:04.129 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "837"

2025-04-25 00:36:13.503 [info] ERROR:pygls.protocol.json_rpc:Failed to handle request 991 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/kh/Proyectos/PE2/ProyectoTareas/tarea.py'), range=63:43-63:43, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 605, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
        new_name=extract_var, **jedi_lines_extract
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
        self._inference_state, self.path, self._module_node,
        new_name, (line, column), until_pos
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 198, in _remove_unwanted_expression_nodes
    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                  ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value

2025-04-25 00:36:13.515 [info] [Error - 12:36:13 a. m.] Request textDocument/codeAction failed.
2025-04-25 00:36:13.515 [info]   Message: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
  Code: -32603 
[object Object]
2025-04-25 00:36:14.252 [info] ERROR:pygls.protocol.json_rpc:Failed to handle request 996 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/kh/Proyectos/PE2/ProyectoTareas/tarea.py'), range=63:44-63:44, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 605, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
        new_name=extract_var, **jedi_lines_extract
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
        self._inference_state, self.path, self._module_node,
        new_name, (line, column), until_pos
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 198, in _remove_unwanted_expression_nodes
    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                  ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value

2025-04-25 00:36:14.253 [info] [Error - 12:36:14 a. m.] Request textDocument/codeAction failed.
2025-04-25 00:36:14.253 [info]   Message: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
  Code: -32603 
[object Object]
2025-04-25 00:36:14.817 [info] ERROR:pygls.protocol.json_rpc:Failed to handle request 999 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/kh/Proyectos/PE2/ProyectoTareas/tarea.py'), range=63:49-63:49, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 605, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
        new_name=extract_var, **jedi_lines_extract
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
        self._inference_state, self.path, self._module_node,
        new_name, (line, column), until_pos
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 198, in _remove_unwanted_expression_nodes
    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                  ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value

2025-04-25 00:36:14.818 [info] [Error - 12:36:14 a. m.] Request textDocument/codeAction failed.
2025-04-25 00:36:14.818 [info]   Message: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
  Code: -32603 
[object Object]
2025-04-25 00:36:46.843 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "1055"

2025-04-25 00:37:42.454 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "1126"

2025-04-25 00:38:28.759 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "1176"

2025-04-25 01:04:33.444 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "1533"

2025-04-25 01:04:35.006 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "1539"

2025-04-25 01:04:37.238 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "1548"

2025-04-25 01:18:05.402 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "1722"

2025-04-25 01:21:54.663 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "2293"

2025-04-25 01:22:35.009 [info] <unknown>:47: SyntaxWarning: invalid escape sequence '\I'

2025-04-25 01:22:35.011 [info] <unknown>:47: SyntaxWarning: invalid escape sequence '\I'

2025-04-25 01:22:35.756 [info] file:///home/kh/Proyectos/PE2/ProyectoTareas/responsable.py:48: SyntaxWarning: invalid escape sequence '\I'

2025-04-25 01:22:48.433 [info] ERROR:pygls.protocol.json_rpc:Failed to handle request 2427 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/kh/Proyectos/PE2/ProyectoTareas/responsable.py'), range=49:15-49:15, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 605, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
        new_name=extract_var, **jedi_lines_extract
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
        self._inference_state, self.path, self._module_node,
        new_name, (line, column), until_pos
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                              ^^^^^^^^^
UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value

2025-04-25 01:22:48.434 [info] [Error - 1:22:48 a. m.] Request textDocument/codeAction failed.
2025-04-25 01:22:48.434 [info]   Message: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
  Code: -32603 
[object Object]
2025-04-25 01:25:43.217 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "2720"

2025-04-25 01:28:36.142 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "2956"

2025-04-25 01:31:10.518 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "3027"

2025-04-25 01:32:32.540 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "3181"

2025-04-25 01:37:57.526 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "3642"

2025-04-25 01:38:11.377 [info] ERROR:pygls.protocol.json_rpc:Failed to handle request 3674 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/kh/Proyectos/PE2/ProyectoTareas/tarea.py'), range=22:37-22:37, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 605, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
        new_name=extract_var, **jedi_lines_extract
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
        self._inference_state, self.path, self._module_node,
        new_name, (line, column), until_pos
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 198, in _remove_unwanted_expression_nodes
    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                  ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value

2025-04-25 01:38:11.379 [info] [Error - 1:38:11 a. m.] Request textDocument/codeAction failed.
2025-04-25 01:38:11.379 [info]   Message: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
  Code: -32603 
[object Object]
2025-04-25 01:38:15.581 [info] ERROR:pygls.protocol.json_rpc:Failed to handle request 3684 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/kh/Proyectos/PE2/ProyectoTareas/tarea.py'), range=22:52-22:52, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 605, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
        new_name=extract_var, **jedi_lines_extract
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
        self._inference_state, self.path, self._module_node,
        new_name, (line, column), until_pos
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 198, in _remove_unwanted_expression_nodes
    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                  ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value

2025-04-25 01:38:15.582 [info] [Error - 1:38:15 a. m.] Request textDocument/codeAction failed.
2025-04-25 01:38:15.582 [info]   Message: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
  Code: -32603 
[object Object]
2025-04-25 01:38:45.042 [info] ERROR:pygls.protocol.json_rpc:Failed to handle request 3730 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/kh/Proyectos/PE2/ProyectoTareas/tarea.py'), range=22:53-22:53, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 605, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
        new_name=extract_var, **jedi_lines_extract
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
        self._inference_state, self.path, self._module_node,
        new_name, (line, column), until_pos
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 198, in _remove_unwanted_expression_nodes
    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                  ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value

2025-04-25 01:38:45.042 [info] [Error - 1:38:45 a. m.] Request textDocument/codeAction failed.
2025-04-25 01:38:45.042 [info]   Message: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
  Code: -32603 
[object Object]
2025-04-25 01:38:46.199 [info] ERROR:pygls.protocol.json_rpc:Failed to handle request 3734 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/kh/Proyectos/PE2/ProyectoTareas/tarea.py'), range=22:52-22:52, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 605, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
        new_name=extract_var, **jedi_lines_extract
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
        self._inference_state, self.path, self._module_node,
        new_name, (line, column), until_pos
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 198, in _remove_unwanted_expression_nodes
    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                  ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value

2025-04-25 01:38:46.200 [info] [Error - 1:38:46 a. m.] Request textDocument/codeAction failed.
2025-04-25 01:38:46.200 [info]   Message: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
  Code: -32603 
[object Object]
2025-04-25 01:39:17.421 [info] ERROR:pygls.protocol.json_rpc:Failed to handle request 3753 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/kh/Proyectos/PE2/ProyectoTareas/tarea.py'), range=22:52-22:52, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 605, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
        new_name=extract_var, **jedi_lines_extract
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
        self._inference_state, self.path, self._module_node,
        new_name, (line, column), until_pos
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 198, in _remove_unwanted_expression_nodes
    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                  ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value

2025-04-25 01:39:17.422 [info] [Error - 1:39:17 a. m.] Request textDocument/codeAction failed.
2025-04-25 01:39:17.422 [info]   Message: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
  Code: -32603 
[object Object]
2025-04-25 01:39:21.029 [info] ERROR:pygls.protocol.json_rpc:Failed to handle request 3772 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/kh/Proyectos/PE2/ProyectoTareas/tarea.py'), range=22:37-22:37, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 605, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
        new_name=extract_var, **jedi_lines_extract
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
        self._inference_state, self.path, self._module_node,
        new_name, (line, column), until_pos
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 198, in _remove_unwanted_expression_nodes
    nodes[0:1] = _remove_unwanted_expression_nodes(nodes[0], pos, until_pos)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                  ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value

2025-04-25 01:39:21.030 [info] [Error - 1:39:21 a. m.] Request textDocument/codeAction failed.
2025-04-25 01:39:21.030 [info]   Message: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
  Code: -32603 
[object Object]
2025-04-25 01:40:42.947 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "3890"

2025-04-25 01:48:53.669 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4459"

2025-04-25 01:48:56.798 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4464"

2025-04-25 01:48:56.845 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4465"

2025-04-25 01:48:57.547 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4466"

2025-04-25 01:49:00.450 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4473"

2025-04-25 01:49:47.042 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4524"

2025-04-25 01:49:58.686 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4544"

2025-04-25 01:50:04.380 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4548"

2025-04-25 01:50:07.143 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4555"

2025-04-25 01:50:16.262 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4562"

2025-04-25 01:50:53.457 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4576"

2025-04-25 01:50:57.381 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4579"

2025-04-25 01:51:12.302 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4595"

2025-04-25 01:51:12.587 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4596"

2025-04-25 01:51:34.749 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4625"

2025-04-25 01:51:36.426 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4631"

2025-04-25 01:51:37.659 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4635"

2025-04-25 01:53:31.581 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "4805"

2025-04-25 01:57:29.171 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5057"

2025-04-25 01:59:07.437 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5134"

2025-04-25 01:59:22.547 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5159"

2025-04-25 01:59:34.583 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5174"

2025-04-25 02:02:26.275 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5343"

2025-04-25 02:02:35.264 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5353"

2025-04-25 02:05:45.133 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5430"

2025-04-25 02:06:03.865 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5472"

2025-04-25 02:06:09.287 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5489"

2025-04-25 02:07:14.566 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5602"

2025-04-25 02:09:34.950 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5740"

2025-04-25 02:18:08.285 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5777"

2025-04-25 02:18:10.373 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5785"

2025-04-25 02:18:16.403 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5802"

2025-04-25 02:18:16.685 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5803"

2025-04-25 02:18:16.724 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5804"

2025-04-25 02:19:04.673 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5906"

2025-04-25 02:19:15.282 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "5929"

2025-04-25 02:19:55.911 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "6021"

2025-04-25 02:26:40.079 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "6262"

2025-04-25 02:27:45.132 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "6333"

2025-04-25 02:28:37.330 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "6389"

2025-04-25 02:28:44.134 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "6395"

2025-04-25 02:28:54.622 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "6416"

2025-04-25 02:28:55.574 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "6420"

2025-04-25 02:29:56.688 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "6543"

2025-04-25 02:31:13.350 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "6605"

2025-04-25 02:31:45.598 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "6657"

2025-04-25 02:36:22.035 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "6927"

2025-04-25 02:36:23.546 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "6933"

2025-04-25 02:40:21.496 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "7103"

2025-04-25 02:40:29.068 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "7119"

2025-04-25 02:40:29.099 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "7120"

2025-04-25 02:43:07.007 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "7249"

2025-04-25 02:43:26.700 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "7267"

2025-04-25 02:43:26.959 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "7268"

2025-04-25 02:44:51.192 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "7286"

2025-04-25 02:46:18.478 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "7432"

2025-04-25 02:47:20.069 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "7536"

2025-04-25 02:47:20.350 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "7537"

2025-04-25 02:49:42.329 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "7731"

2025-04-25 02:49:42.590 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "7732"

2025-04-25 02:50:15.524 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "7758"

2025-04-25 03:20:54.204 [info] ERROR:pygls.protocol.json_rpc:Failed to handle request 8206 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/kh/Proyectos/PE2/ProyectoTareas/gestor.py'), range=201:20-201:23, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 605, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
        new_name=extract_var, **jedi_lines_extract
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
        self._inference_state, self.path, self._module_node,
        new_name, (line, column), until_pos
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 199, in _remove_unwanted_expression_nodes
    nodes[-1:] = _remove_unwanted_expression_nodes(nodes[-1], pos, until_pos)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                              ^^^^^^^^^
UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value

2025-04-25 03:20:54.205 [info] [Error - 3:20:54 a. m.] Request textDocument/codeAction failed.
2025-04-25 03:20:54.205 [info]   Message: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
  Code: -32603 
[object Object]
2025-04-25 03:20:54.747 [info] ERROR:pygls.protocol.json_rpc:Failed to handle request 8208 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/kh/Proyectos/PE2/ProyectoTareas/gestor.py'), range=201:20-201:22, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 605, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
        new_name=extract_var, **jedi_lines_extract
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
        self._inference_state, self.path, self._module_node,
        new_name, (line, column), until_pos
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 199, in _remove_unwanted_expression_nodes
    nodes[-1:] = _remove_unwanted_expression_nodes(nodes[-1], pos, until_pos)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                              ^^^^^^^^^
UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value

2025-04-25 03:20:54.748 [info] [Error - 3:20:54 a. m.] Request textDocument/codeAction failed.
2025-04-25 03:20:54.748 [info]   Message: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
  Code: -32603 
[object Object]
2025-04-25 03:21:03.207 [info] ERROR:pygls.protocol.json_rpc:Failed to handle request 8222 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/kh/Proyectos/PE2/ProyectoTareas/gestor.py'), range=201:56-201:58, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ~~~~~~~^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi_language_server/server.py", line 605, in code_action
    extract_variable_refactoring = jedi_script.extract_variable(
        new_name=extract_var, **jedi_lines_extract
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/__init__.py", line 628, in extract_variable
    return extract_variable(
        self._inference_state, self.path, self._module_node,
        new_name, (line, column), until_pos
    )
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 19, in extract_variable
    nodes = _find_nodes(module_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 87, in _find_nodes
    nodes = _remove_unwanted_expression_nodes(parent_node, pos, until_pos)
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 199, in _remove_unwanted_expression_nodes
    nodes[-1:] = _remove_unwanted_expression_nodes(nodes[-1], pos, until_pos)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kh/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/python_files/lib/jedilsp/jedi/api/refactoring/extract.py", line 196, in _remove_unwanted_expression_nodes
    nodes = nodes[start_index:end_index + 1]
                              ^^^^^^^^^
UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value

2025-04-25 03:21:03.208 [info] [Error - 3:21:03 a. m.] Request textDocument/codeAction failed.
2025-04-25 03:21:03.208 [info]   Message: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
  Code: -32603 
[object Object]
2025-04-25 03:21:05.156 [info] WARNING:pygls.protocol.json_rpc:Cancel notification for unknown message id "8223"

